// Generated by IB v0.3.0 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation AppDelegate

@end


@implementation MainWindow

@end


@implementation AppDelegate

@end



