// Generated by IB v0.3.0 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>
#import <UIKit/UIKit.h>

@interface AppDelegate





-(IBAction) applicationDidFinishLaunching:(id) notification;
-(IBAction) buildWindow;

@end


@interface MainWindow: NSWindowController

@property IBOutlet NSButton * button;



-(IBAction) windowDidLoad;
-(IBAction) foo:(id) sender;

@end


@interface AppDelegate





-(IBAction) buildMenu;

@end



